.travis.yml
tox.ini

Created `.travis.yml`, shuffled some things around in `tox.ini`, and removed `pypy3` as an environment. (The latter two were to facilitate clean Travis builds)

Adding TravisCI support

---

fuzz_lightyear/request.py
testing/vulnerable_app/app.py
testing/vulnerable_app/util.py
testing/vulnerable_app/views/location.py
testing/vulnerable_app/views/types.py
tests/integration/request_test.py

This PR addresses issue #22.
Previously, array parameters in paths were treated as strings, leading to improper encoding. This adds support for URL encoding arrays.
Swagger supports 4 types of separators in path arrays: commas, spaces, pipes, and tabs ([source](https://swagger.io/docs/specification/2-0/describing-parameters/#array-and-multi-value-parameters)). The type is specified in the `collectionFormat` of the parameter, and the `collectionFormat` is checked when formatting the URL in `fuzz_lightyear/request.py`.
I added a test for a simple `csv` case as an example of how the formatting works- adding tests for `ssv`, `tsv`, and `pipes` seemed superfluous due there being no additional logic surrounding those formats.

URL encode path array variables

---

fuzz_lightyear/fuzzer.py
tests/integration/fuzzer_test.py

This PR address issue #5. 
`hypothesis` has support for setting (inclusive) upper and lower bounds for integer and numbers. We might have to be a bit more creative when addressing the other [specification for integers](https://swagger.io/docs/specification/data-models/data-types/#numbers), `multipleOf`.
Added a small test for fuzzing integers to confirm it works.

Add support for setting bounds for integer fuzzing

---

README.md
fuzz_lightyear/__init__.py
fuzz_lightyear/datastore.py
fuzz_lightyear/main.py
fuzz_lightyear/supplements/setup.py
tests/unit/supplements/setup_supplements_test.py

This PR addresses issue #16 .
The setup code is treated like any other fixture, and can be included in the file with all other fixtures. Right now it doesn't support setup functions that take in arguments. If that's the case, I'm imagining a tuple of `(func, args, kwargs)` or a dictionary where `func` maps to `(args, kwargs)`.

Add setup fixture for code execution prior to testing

---

README.md
fuzz_lightyear/fuzzer.py
fuzz_lightyear/main.py
fuzz_lightyear/settings.py
fuzz_lightyear/usage.py

This PR addresses issue #2.
Add a `--disable-unicode` flag, and only fuzz with ASCII characters when the flag is included. This PR adds an addition `unicode_enabled` setting to `Settings()`, and its default is true.

Add --disable-unicode flag

---

README.md
fuzz_lightyear/__init__.py
fuzz_lightyear/datastore.py
fuzz_lightyear/request.py
fuzz_lightyear/supplements/factory.py
fuzz_lightyear/supplements/hooks.py
fuzz_lightyear/util.py
tests/conftest.py
tests/integration/request_test.py
tests/unit/datastore_test.py
tox.ini

This makes it so that developers can add their own headers and parameters to fuzzing requests, in case the Swagger spec is intentionally incomplete (some more details are available on internal Slack).
TODO: Actually provide an interface for developers to create hooks.
-----
I also moved a bunch of the fuzzing code to its own function to try to reduce nesting.

Add post fuzz hooks

---

fuzz_lightyear/main.py
fuzz_lightyear/usage.py
requirements-minimal.txt
requirements.txt
setup.py
tests/integration/main_test.py

Before, the `--schema` flag only allowed json files. This change makes it so that the `--schema` flag can accept yaml files. We now use pyyaml to load the yaml file as a python dict and pass the dict to bravado. This is the same approach as JSON files.
If a file doesn't have a `json`, `yaml` or `yml` file extension, we'll try to load the file as json and yaml, and only raise an exception if the file can't be loaded either way.

Support yaml swagger schema in`--schema`

---

fuzz_lightyear/generator.py
tests/integration/generator_test.py

**WIP**
This PR will be a hybrid of what is described in issue #8 and what is described in the [original research paper](https://arxiv.org/pdf/1806.09739.pdf). 
We'll start with the assumption that requests produce and consume single values: e.g. endpoint `/a` produces an integer `num` and `/b` consumes an integer `num`. For simplicity's sake, this is ignoring the case where some endpoint `/c` produces a dictionary that contains an integer `num` as one of its values.
To begin building a request graph, we need to know what endpoints produce and consume what values. So, two dictionaries are built: one that maps `operation_id`s to the resources they consume, and one that maps resources to the `operation_id`s that will produce them. 
From there, we construct a directed request graph. Every …

Improve test discovery algorithm

---

fuzz_lightyear/fuzzer.py
fuzz_lightyear/request.py
requirements-dev.txt
requirements-minimal.txt
requirements.txt
setup.py

See https://github.com/Yelp/fuzz-lightyear/issues/40.
Fuzz-lightyear uses Hypothesis's internal APIs, which have changed recently. This updates the required version of Hypothesis to a more recent one, and updates the imports to prevent errors.

Update functions to use newer version of Hypothesis

---

README.md
fuzz_lightyear/datastore.py
fuzz_lightyear/request.py
fuzz_lightyear/supplements/hooks.py
tests/conftest.py
tests/integration/request_test.py
tests/unit/datastore_test.py

While trying to add this internally, I found a use case where we need to rerun a hook. Specifically, when a server reads a nonce from the request, we need to regenerate this nonce on every new request. If this nonce is generated by a hook, then we can just re-run the hook to generate the nonce.
This PR adds a `rerun` parameter to the hook decorator so that fuzz-lightyear can rerun the hook if the same request is sent twice. Test included.
TODO: readme

Add rerun flag to post-fuzz hooks

---

requirements-dev.txt
tests/conftest.py

* Bump jinja to a version that doesn't cause the `collections.abc` is moved in py38 warning
* Set `sys.ps1=''` in tests so that Hypothesis thinks that we're in an interactive session, thus silencing an error that we can't really get around

Reduce test noisiness

---

fuzz_lightyear/generator.py
fuzz_lightyear/main.py
fuzz_lightyear/request.py

In running these tests, I got really annoyed at the amount of unnecessary `hypothesis` warnings:
```
.../virtualenv_run/lib/python3.6/site-packages/hypothesis/strategies/_internal/strategies.py:273: NonInteractiveExampleWarning: The `.example()` met
hod is good for exploring strategies, but should only be used interactively.  We recommend using `@given` for tests - it performs better, saves and replays failures to avoid flakiness,
and reports minimal examples. (strategy: fixed_dictionaries({'business_id': builds(type_cast)}))
NonInteractiveExampleWarning,
```
Let's just filter them out.

Filter out hypothesis warnings

---

fuzz_lightyear/main.py
fuzz_lightyear/output/color.py
fuzz_lightyear/output/interface.py
fuzz_lightyear/settings.py

ANSI colorization is only good if the output is to a terminal. When it goes into a file instead, the ANSI color codes makes it hard to read. This fixes that.
Manual testing.
**Before Change**:
```
$ make vulnerable_app
$ fuzz-lightyear http://localhost:5000/schema -f test_data > output.fuzz
$ vim output.fuzz
^[[1m======================= fuzzing session starts =======================^[[0m
Hypothesis Seed: 45681616869573565430211526758451148904
basic ^[[92m.^[[0m^[[91mE^[[0m^[[91mE^[[0m
```
**After Change**:
```
$ make vulnerable_app
$ fuzz-lightyear http://localhost:5000/schema -f test_data > output.fuzz
$ vim output.fuzz
======================= fuzzing session starts =======================
Hypothesis Seed: 242999052542582450454317716917191761814
basic .EE
```
We could probably create a …

Disable color printing when not printing to terminal

---

fuzz_lightyear/main.py
fuzz_lightyear/output/formatter.py
fuzz_lightyear/supplements/exclude.py
fuzz_lightyear/usage.py
test_data/nested/another_fixture.py
tests/conftest.py
tests/integration/main_test.py
tox.ini

There's a nuanced difference between `fuzz_lightyear.exclude.operations` and `fuzz_lightyear.exclude.non_vulnerable_operations`: the former skips over the endpoint completely, and the latter tests the endpoint, but ignores the `IDORPlugin` result.
This nuance makes an important difference when generating sequences of length n>1, or when the Swagger schema is incorrect. If the endpoint is completely excluded, the test run will be faster, since there are less total sequences to create. Furthermore, invalid Swagger schemas will be ignored as well.
For the times we want this trade-off, this PR introduces the new flag `--ignore-non-vulnerable`, which will treat excluded `non_vulnerable_operations` as completely excluded operations.

adding --ignore-non-vulnerable flag

---

fuzz_lightyear/output/formatter.py

This fixes this traceback:
```
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/nail/home/aaronloo/pg/msg_pages/fuzzing/main.py", line 100, in <module>
main()
File "/nail/home/aaronloo/pg/msg_pages/fuzzing/main.py", line 96, in main
return run_fuzz_lightyear(sys.argv[1:])
File "/nail/home/aaronloo/pg/msg_pages/virtualenv_run/lib/python3.6/site-packages/fuzz_lightyear/main.py", line 47, in main
outputter.show_results()
File "/nail/home/aaronloo/pg/msg_pages/virtualenv_run/lib/python3.6/site-packages/fuzz_lightyear/output/interface.py", line 108, in show_results
datetime.now() - self.start_time,
File …
```

Gracefully handling case of no tests run

---

fuzz_lightyear/result.py
tests/integration/generator_test.py
tests/integration/result_test.py

This addresses #56 with automated test cases.

bug fix: sequences are marked successful only if they complete

---

tox.ini

Sometimes it's not necessary to run all tests. This change allows to pass arguments to pytest (e.g. `tox -- tests/integration/result_test.py`) meanwhile keeps running all tests by default.

Pass positional arguments to pytest

---

fuzz_lightyear/generator.py
testing/vulnerable_app/views/sequence.py
tests/integration/generator_test.py

The generated graph from swagger docs only considers 200 as success response code. 
For the purpose of fuzz-lightyear, `201` is another useful response code mainly used for `create` apis. 
- Existing test passes
- Added new test for existing api in [`vulnerable_app`](https://github.com/Yelp/fuzz-lightyear/tree/master/testing/vulnerable_app)

Update generator to consider 201 as success response code

---

.github/workflows/pypi.yml

- Setup Github workflows for publishing to PyPI
- Github Action will use [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi) in PyPI for security; so no `username/token` should be required

Setup Github workflows for publishing to PyPI

---

.github/workflows/pypi.yml

- The version set for `gh-action-pypi-publish` is 3 years old and the deploy is failing. 
- Setting the version to `@release/v1` as mentioned here: https://github.com/marketplace/actions/pypi-publish

Update Github action PyPi publish version

---

setup.py

- Publish to PyPI [workflow](https://github.com/Yelp/fuzz-lightyear/actions/runs/7827988649/job/21356943209) fails with below error:
```sh
ERROR    `long_description` has syntax errors in markup and would not be        
rendered on PyPI.                                                      
No content rendered from RST source. 
```
- Although, we don't have `long_description` field in `setup.py`, workflow fails 
- Some discussions have suggested to add `long_description_content_type` to fix this error
- https://github.com/pypa/gh-action-pypi-publish/discussions/191
- https://github.com/pypa/gh-action-pypi-publish/discussions/209
- Adding `long_description` field along with content_type for better description in the pypi project page

Fix: 'long_description' error when publishing to PyPI
